// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Messages
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_MESSAGE = "GET_MESSAGE";

// Errors
export const GET_ERRORS = 'GET_ERRORS';

// Tasks
export const GET_TASKS = 'GET_TASK';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_COMPLETION = 'UPDATE_COMPLETION';
export const FETCH_COMPLETED_TASKS_COUNT_SUCCESS = 'FETCH_COMPLETED_TASKS_COUNT_SUCCESS';
export const FETCH_COMPLETED_TASKS_COUNT_FAIL = 'FETCH_COMPLETED_TASKS_COUNT_FAIL';
export const FETCH_UNFINISHED_TASKS_COUNT_SUCCESS = 'FETCH_UNFINISHED_TASKS_COUNT_SUCCESS';
export const FETCH_UNFINISHED_TASKS_COUNT_FAIL = 'FETCH_UNFINISHED_TASKS_COUNT_FAIL';

// Discussion
export const DISCUSSION_MAIN = 'DISCUSSION_MAIN';
export const GET_DISCUSSION = 'GET_DISCUSSION';
export const CREATE_DISCUSSION = 'CREATE_DISCUSSION';
export const POST_SENT = 'POST_SENT';
//export const GET_DISCUSSIONS = 'GET_DISCUSSIONS';
export const CREATE_DISCUSSIONUSER = 'CREATE_DISCUSSIONUSER';
export const UPDATE_DISCUSSION = 'UPDATE_DISCUSSION';

// Calendar
export const GET_EVENTS = 'GET_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const ADD_EVENT_TO_ALL = 'ADD_EVENT_TO_ALL';
export const FETCH_ATTENDED_MEETINGS_COUNT_SUCCESS = 'FETCH_ATTENDED_MEETINGS_COUNT_SUCCESS';
export const FETCH_ATTENDED_MEETINGS_COUNT_FAIL = 'FETCH_ATTENDED_MEETINGS_COUNT_FAIL';
export const FETCH_UNATTENDED_MEETINGS_COUNT_SUCCESS = 'FETCH_UNATTENDED_MEETINGS_COUNT_SUCCESS';
export const FETCH_UNATTENDED_MEETINGS_COUNT_FAIL = 'FETCH_UNATTENDED_MEETINGS_COUNT_FAIL';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';

export const GET_DISCUSSIONS = 'GET_DISCUSSIONS';
export const ADD_DISCUSSION = 'ADD_DISCUSSION';
export const GET_MESSAGES = 'GET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const FETCH_USERNAMES_SUCCESS = 'FETCH_USERNAMES_SUCCESS';
export const FETCH_USERNAMES_FAIL = 'FETCH_USERNAMES_FAIL';

// Reset Password
export const PASSWORD_RESET_EMAIL_SENT = 'PASSWORD_RESET_EMAIL_SENT';
export const PASSWORD_RESET_EMAIL_FAIL = 'PASSWORD_RESET_EMAIL_FAIL';

export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS';
export const SET_NEW_PASSWORD_FAIL = 'SET_NEW_PASSWORD_FAIL';

// Notifications
export const EMAIL_NOTIFICATION_SENT = 'EMAIL_NOTIFICATION_SENT';
export const EMAIL_NOTIFICATION_FAIL = 'EMAIL_NOTIFICATION_FAIL';
