# Generated by Django 5.0 on 2024-02-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calendar_app",
            "0003_remove_meeting_event_ptr_remove_event_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="allDay",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="endTime",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="startTime",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
