# Generated by Django 5.0 on 2024-02-09 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0004_alter_event_allday_alter_event_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="event",
            name="theme",
        ),
    ]
