# Generated by Django 5.0 on 2024-02-09 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "calendar_app",
            "0005_remove_event_description_remove_event_participants_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="endTime",
        ),
        migrations.RemoveField(
            model_name="event",
            name="startTime",
        ),
    ]
