# Generated by Django 5.0 on 2024-02-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0006_remove_event_endtime_remove_event_starttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="allDay",
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
