# Generated by Django 5.0 on 2024-03-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0008_alter_event_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attended",
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
