# Generated by Django 5.0 on 2024-03-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0010_event_completed_at_event_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
