# Generated by Django 5.0 on 2024-03-18 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0011_event_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="description",
            new_name="extendedProps",
        ),
    ]
