# Generated by Django 5.0 on 2024-03-18 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0012_rename_description_event_extendedprops"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="extendedProps",
            new_name="description",
        ),
    ]
