# Generated by Django 5.0 on 2024-04-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0013_rename_extendedprops_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
