# Generated by Django 5.0.2 on 2024-03-15 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must start with 3 uppercase letters denoting company followed by 3 digits.', regex='^[A-Z]{3}\\d{3}$')]),
        ),
    ]
