# Generated by Django 5.0 on 2024-03-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0005_choices_remove_customuser_notifyabout_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="notifyAbout",
        ),
        migrations.AddField(
            model_name="customuser",
            name="notifyforEvents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="notifyforMessages",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="notifyforTasks",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Choices",
        ),
    ]
