# Generated by Django 5.0 on 2024-03-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0006_remove_customuser_notifyabout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="notifyThrough",
            field=models.CharField(default="Messages", max_length=9),
        ),
    ]
