# Generated by Django 5.0 on 2023-12-08 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions_app', '0002_remove_discussion_users_discussion_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='users',
        ),
        migrations.AddField(
            model_name='discussion',
            name='users',
            field=models.ManyToManyField(related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
